### ISSUE TITLE
wont run, probably me

### ISSUE THREAD

**Issue by danblah** [throneless-tech/monitor-parse#1]
blah@penguin:~/projects/pdf2feed$ npm run parse -- -i 11-9\ Monitoring\ .pdf

> pdf2feed@1.0.0 parse
> node ./index.mjs "-i" "11-9 Monitoring .pdf"

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from /home/blah/projects/pdf2feed/index.mjs
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code 1
npm ERR! path /home/blah/projects/pdf2feed
npm ERR! command failed
npm ERR! command sh -c node ./index.mjs "-i" "11-9 Monitoring .pdf"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/blah/.npm/_logs/2021-11-10T19_14_22_591Z-debug.log

LOG
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/bin/npm',
0 verbose cli   'run',
0 verbose cli   'parse',
0 verbose cli   '--',
0 verbose cli   '-i',
0 verbose cli   '11-9 Monitoring .pdf'
0 verbose cli ]
1 info using npm@7.5.2
2 info using node@v12.22.5
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/blah/projects/pdf2feed/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/blah/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 15ms
19 verbose npm-session 37c707fd201f5756
20 timing npm:load Completed in 30ms
21 timing command:run-script Completed in 280ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid pdf2feed@1.0.0
24 verbose cwd /home/blah/projects/pdf2feed
25 verbose Linux 5.4.139-16311-g330b3df0010b
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "parse" "--" "-i" "11-9 Monitoring .pdf"
27 verbose node v12.22.5
28 verbose npm  v7.5.2
29 error code 1
30 error path /home/blah/projects/pdf2feed
31 error command failed
32 error command sh -c node ./index.mjs "-i" "11-9 Monitoring .pdf"
33 verbose exit 1

**Comment by jheretic** [comment]
Are you sure you ran `npm install` from the pdf2feed directory first? If not we'll test it against Nodejs v12 in case there's an incompatibility (it's failing to load `fs`, a built-in, and I have a slightly newer version of Nodejs).
